#!/bin/bash

# This is a setup script that is intented to run as the root of all other scripts
# The idea is that this is the only place required for init. Once this script runs all systems should be working.
# -------------------- Git Submodules ------------------------------------------
git submodule update

# -------------------- Home Folder Links ---------------------------------------
ln -sf "$PWD/.zshenv" "${HOME}/.zshenv"
ln -sf "$PWD/.zshrc" "${HOME}/.zshrc"
ln -sf "$PWD/.zsh" "$HOME/.zsh"
ln -sf "$PWD/rbenv" "$HOME/.rbenv"
ln -sf "$PWD/nvm" "$HOME/.nvm"

mkdir -p "$HOME"/.config
ln -sf "$PWD/nvim" "$HOME/.config/nvim"
ln -sf "$PWD/sway" "$HOME/.config/sway"
ln -sf "$PWD/waybar" "$HOME/.config/waybar"
ln -sf "$PWD/foot" "$HOME/.config/foot"
ln -sf "$PWD/rofi" "$HOME/.config/rofi"
ln -sf "$PWD/swayosd" "$HOME/.config/swayosd"

# Don't link tmux. It will come from the profile
# ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/tmux" "$HOME/.tmux"
# ln -sf "$PWD/rbenv" "$HOME/.rbenv"

# -------------------- HushLogin -----------------------------------------------
touch "${HOME}"/.hushlogin

# -------------------- Setup Paths ---------------------------------------------
cp -u "$PWD/.paths.template" "$HOME/.paths"

# -------------------- neovim --------------------------------------------------
# If we don't have neovim download it. Many distros have old versions that are
# next to useless.
if ! command -v "nvim" &>/dev/null; then
  neovim_download_location="https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz"
  download_dir="/tmp"
  download_filename="neovim.tar.gz"
  curl -L "$neovim_download_location" -o "$download_dir/$download_filename"
  tar -xzf "$download_dir/$download_filename" -C "/usr/local" --strip-components=1
  rm "$download_dir/$download_filename"
fi

# Load the profile
profile "gruvbox-dark"

# Install the plugins
nvim --headless "+Lazy! sync" +qa
nvim --headless "+TSUpdate" +qa
