# frozen_string_literal: true

source 'https://rubygems.org'

gem 'debug', '>= 1.0.0'
gem 'minitest', '~> 5.20', group: :development
gem 'pry'
gem 'rake'
gem 'rubocop', require: false
gem 'rubocop-sorbet', require: false
gem 'solargraph', group: :development
gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, group: :development
gem 'unparser', require: false
