#!/bin/bash

# Read the first parameter (option)
option="$1"
shift

# Perform actions based on the option
case "$option" in
    "note")
        exec $EDITOR "$(echo "$*" | zet-note)"
        ;;
    "ls")
        find "$ZET_HOME" -type f -regex ".*\.\md"
        ;;
    *)
        echo "Invalid option: $option"
        echo "Available options: note, ls"
        ;;
esac
